services:
  - type: web
    name: utkarsh-toss-book
    env: node
    buildCommand: npm run build
    startCommand: node backend/server.js
    envVars:
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        value: utkarsh_toss_book_secret_key_2024
      - key: NODE_ENV
        value: production
      - key: npm_config_legacy_peer_deps
        value: true
      - key: npm_config_engine_strict
        value: false
